### ISSUE TITLE
IncRename backspace issue

### ISSUE THREAD

**Issue by BushMiner** [WizardStark/dotfiles#5]
The new IncRename is great but if you backspace all the way in the popup it jumps to the vim command line and starts deleting the command itself. Is there a way to make it stop deleting before this happens?

**Comment by WizardStark** [comment]
Without the nvim issue mentioned in https://github.com/smjonas/inc-rename.nvim/issues/33 being resolved I do not see how this is possible as the hotkey is simply ":IncRename <arg>", and as such pressing backspace will return to the commandline. If command-preview and command mode are split then this will likely be solved - probably in the IncRename plugin itself.

**Comment by WizardStark** [comment]
Resolved by no longer using IncRename
